# Generated by Django 3.2.8 on 2021-10-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_register', models.CharField(max_length=20, verbose_name='number_register')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('responsible_1', models.CharField(max_length=100, verbose_name='responsible_1')),
                ('responsible_2', models.CharField(max_length=100, verbose_name='responsible_2')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('accept_1', models.BooleanField(verbose_name='accept_1')),
                ('accept_2', models.BooleanField(verbose_name='accept_2')),
                ('accept_3', models.BooleanField(verbose_name='accept_3')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date_creation')),
            ],
        ),
        migrations.CreateModel(
            name='NumbersRegisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_register', models.CharField(max_length=20, verbose_name='number_register')),
                ('function_first', models.CharField(max_length=100, verbose_name='function_first')),
                ('function_second', models.CharField(max_length=100, verbose_name='function_second')),
                ('function_third', models.CharField(max_length=100, verbose_name='function_third')),
                ('section', models.CharField(max_length=100, verbose_name='section')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date_creation')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_register', models.CharField(max_length=20, verbose_name='number_register')),
                ('name_skill', models.CharField(max_length=100, verbose_name='name_skill')),
                ('type_skill', models.CharField(max_length=100, verbose_name='type_skill')),
                ('name_person', models.CharField(max_length=100, verbose_name='name_person')),
                ('type_person', models.CharField(max_length=100, verbose_name='type_person')),
                ('notes', models.CharField(max_length=100, verbose_name='notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date_creation')),
            ],
        ),
    ]
